config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboards#index'

  get 'dashboard', to: 'dashboards#index'

  get 'test', to: 'tests#index'

  resources :dashboards
  resources :tracks
  resources :categories
  resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :tracks, dependent: :destroy
  has_one_attached :photo_url


  validates :name, presence: true,
            length:{minimum:3 , maximum: 50}
  validates :photo_url, presence: true
  validates :photo_url, attached: true,
            content_type: [:png, :jpg, :jpeg],
            size: { less_than: 10.megabytes , message: 'is not given between size' }

  validates :dob, presence: true
  validates :youth_name, presence: true
  validates :born_city, presence: true
  validates :bio, presence: true,
            length:{minimum:20 , maximum: 1000}



end

app/models/category.rb
class Category < ApplicationRecord

  has_many :tracks, dependent: :destroy

  validates :name, presence:true

end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :artist
  belongs_to :category
  has_one_attached :track_url
  has_one_attached :image_url
  has_one_attached :translate_text

  validates :name, presence: true
  validates :length, presence: true
  validates :description, presence: true
  validates :translate_text, presence: true
  validates :translate_text, attached: true,
            size: { less_than: 1.megabytes , message: 'is not given between size' }
  validates :category_id, presence: true
  validates :artist_id, presence: true
  validates :image_url, presence: true
  validates :image_url, attached: true,
            content_type: [:png, :jpg, :jpeg],
            size: { less_than: 10.megabytes , message: 'is not given between size' }
  validates :track_url, presence: true
  validates :track_url, attached: true,
            content_type: ['audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio'],
            size: { less_than: 40.megabytes , message: 'is not given between size' }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true,
            uniqueness: true,
            length: {minimum:3 , maximum: 30}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:edit,:update, :show, :destroy]
  before_action :authenticate_user!

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      flash[:success] = "Artist was successfully created"
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @artist.update(artist_params)
      flash[:success] = "Artist was successfully updated"
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    flash[:danger] = "Artist was successfully deleted"
    redirect_to artists_path
  end

  private

    def artist_params
      params.require(:artist).permit(:name,:born_city,:youth_name,:bio,:dob,:photo_url)

    end

    def set_artist
      @artist = Artist.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit,:update, :show, :destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category was successfully updated"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = "Category was successfully deleted"
    redirect_to categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index

  end

  def show

  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :set_tracks, only: [:edit,:update, :show, :destroy]
  before_action :authenticate_user!

  def index
    @tracks = Track.all
  end

  def show

  end

  def new
    @track = Track.new
    @categories = Category.all
    @artists = Artist.all
  end

  def create
    @track = Track.create(track_params)
    @categories = Category.all
    @artists = Artist.all
    if @track.save
      flash[:success] = "Track was successfully created"
      redirect_to tracks_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    @artists = Artist.all
  end

  def update
    @categories = Category.all
    @artists = Artist.all
    if @track.update(track_params)
      flash[:success] = "Track was successfully updated"
      redirect_to tracks_path
    else
      render :edit
    end
  end

  def destroy
    @track.destroy
    flash[:danger] = 'Track was successfully deleted.'
    redirect_to tracks_path
  end

  private

    def track_params
      params.require(:track).permit(:name,:description,:translate_text,:length,:category_id,:artist_id,:track_url,:image_url)

    end

    def set_tracks
      @track = Track.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name, class_name = nil)
        if params[:controller] == controller_name
         class_name == nil ? "active" : class_name
        else
           nil
        end
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/views/artists/_form.html.erb
<div class="ibox-content">
  <%= form_for @artist, :html=>{:class => "form-horizontal"} do |f| %>
    <div class="form-group"><label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
          <%= f.text_field :name, class:"form-control"%>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Young Name</label>
        <div class="col-sm-10">
          <%= f.text_field :youth_name, class:"form-control"%>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Born City</label>
        <div class="col-sm-10">
          <%= f.text_field :born_city, class:"form-control"%>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Date of Birth</label>
        <div class="col-sm-10">
          <%= f.date_field :dob, class:"form-control" %>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Photo Upload</label>
        <div class="col-sm-10">
          <%= f.file_field :photo_url, class:"form-control" %>
        </div>
    </div>


    <div class="form-group"><label class="col-sm-2 control-label">Artist Biography</label>
        <div class="col-sm-10">
          <%= f.text_area :bio, class:"form-control summernote"%>

        </div>
    </div>

    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-2">
            <%= link_to "Cancel", categories_path, class: "btn btn-white"%>
            <%= f.submit(@artist.new_record? ? "Create Artist" : "Edit Artist", class: "btn btn-primary")%>
        </div>
    </div>
  <% end %>
</div>

<% content_for :javascript do %>
<script type="text/javascript">


$(function() {
    $('.summernote').summernote();
});

</script>
<% end %>

app/views/artists/edit.html.erb
<%= render '/layouts/errors', obj: @artist%>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Edit New Category</h5>
            </div>
            <div class="ibox-content">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/artists/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
        <h2>Artists

        </h2>
        <ol class="breadcrumb">
          <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'index' %>">Home</a>
          </li>
          <li class="active">
              <strong>Category List</strong>
          </li>
        </ol>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
      <div class="col-lg-12">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5>Artist List</h5>
                  <div class="ibox-tools">
                    <%= link_to "Create", new_artist_path, class:"btn btn-info btn-xs"%>
                    </div>
              </div>
              <div class="ibox-content">
                  <table class="table">
                      <thead>
                      <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Tracks Count</th>
                          <th>Action</th>
                      </tr>
                      </thead>
                      <tbody>
                      <% @artists.each do |artist|%>
                        <tr>
                            <td><%= artist.id%></td>
                            <td><%= artist.name%></td>
                            <td><%= artist.tracks.count%></td>
                            <td>
                              <%= link_to "show", artist_path(artist), class:"btn btn-primary btn-xs" %>
                              <%= link_to "Edit", edit_artist_path(artist), class:"btn btn-info btn-xs" %>
                              <%= link_to "Delete", artist_path(artist), method: :delete, data: {confirm: "Are you sure to delete artist?"}, class:"btn btn-danger btn-xs"%>
                            </td>
                        </tr>
                      <% end %>
                      </tbody>
                  </table>

              </div>
          </div>
      </div>
  </div>
</div>

app/views/artists/new.html.erb
<%= render '/layouts/errors', obj: @artist%>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Create New Artist</h5>
            </div>
            <div class="ibox-content">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag(url_for(@artist.photo_url.variant(resize: "400x400")))  if @artist.photo_url.attached?%>

app/views/categories/_form.html.erb
<div class="ibox-content">
  <%= form_for @category, :html=>{:class => "form-horizontal"} do |f| %>
    <div class="form-group"><label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
          <%= f.text_field :name, class:"form-control"%>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-2">
            <%= link_to "Cancel", categories_path, class: "btn btn-white"%>
            <%= f.submit(@category.new_record? ? "Create Categroy" : "Edit Category", class: "btn btn-primary")%>
        </div>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render '/layouts/errors', obj: @category%>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Edit Category</h5>
            </div>
            <div class="ibox-content">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
        <h2>Category

        </h2>

        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'index' %>">Home</a>
        </li>
        <li class="active">
            <strong>Category List</strong>
        </li>
    </ol>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
      <div class="col-lg-12">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5>Category List</h5>
                  <div class="ibox-tools">
                    <%= link_to "Create", new_category_path, class:"btn btn-info btn-xs"%>
                  </div>
              </div>
              <div class="ibox-content">
                  <table class="table">
                      <thead>
                      <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Tracks Count</th>
                          <th>Action</th>
                      </tr>
                      </thead>
                      <tbody>
                      <% @categories.each do |category|%>
                        <tr>
                            <td><%= category.id%></td>
                            <td><%= category.name%></td>
                            <td><%= category.tracks.count%></td>
                            <td>
                              <%= link_to "show", category_path(category), class:"btn btn-primary btn-xs" %>
                              <%= link_to "Edit", edit_category_path(category), class:"btn btn-info btn-xs" %>
                              <%= link_to "Delete", category_path(category), method: :delete, data: {confirm: "Are you sure to delete category?"}, class:"btn btn-danger btn-xs"%>
                            </td>
                        </tr>
                      <% end %>
                      </tbody>
                  </table>

              </div>
          </div>
      </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render '/layouts/errors', obj: @category%>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Create New Category</h5>
            </div>
            <div class="ibox-content">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 align="center">
  <%= @category.name%>
</h1>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-4">
    <div class="widget red-bg p-lg text-center">
            <div class="m-b-md">
                <i class="fa fa-music fa-4x"></i>
                <h1 class="m-xs"><%= @category.tracks.count%></h1>
                <h3 class="font-bold no-margins">
                    Tracks
                </h3>
           <small>total track count</small>
       </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="widget blue-bg p-lg text-center">
            <div class="m-b-md">
                <i class="fa fa-play fa-4x"></i>
                <h1 class="m-xs"><%= 10%></h1>
                <h3 class="font-bold no-margins">
                    Users
                </h3>
           <small>total user play count</small>
       </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="widget yellow-bg p-lg text-center">
            <div class="m-b-md">
                <i class="fa fa-fast-forward fa-4x"></i>
                <h1 class="m-xs"><%= 10%></h1>
                <h3 class="font-bold no-margins">
                    Pa Yate
                </h3>
           <small>top track play count</small>
       </div>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<h1>Show Dashboard</h1>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>
                  <%= "#{pluralize(obj.errors.count,"error")}"%>
                </h5>
            </div>
            <div class="ibox-content">
                <% obj.errors.full_messages.each do |msg| %>
                  <div class="alert alert-danger">
                      <%= msg%>
                  </div>
                <% end %>

            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2015
    </div>
</div>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |name,msg| %>
      <% type = name.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="<%= image_url 'profile_small.jpg' %>"/>
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">David Williams</strong>
                            </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="">Logout</a>
                        </li>
                    </ul>
                </div>
                <div class="logo-element">
                    TaYar+
                </div>
            </li>
            <li class="<%= is_active_controller('dashboards') %>">
                <%= link_to '/dashboards' do %>
                    <i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Dashboards</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('artists') %>">
                <%= link_to '/artists' do %>
                    <i class="fa fa-user-o"></i> <span class="nav-label" data-i18n="nav.artists">Artists</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('tracks') %>">
                <%= link_to '/tracks' do %>
                    <i class="fa fa-music"></i> <span class="nav-label" data-i18n="nav.track">Tracks</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('categories') %>">
                <%= link_to '/categories' do %>
                    <i class="fa fa-th-list"></i> <span class="nav-label" data-i18n="nav.category">Categories</span>
                <% end %>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="pull-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>


            <li>
                    <%= link_to 'Log Out', destroy_user_session_path, class:"fa fa-sign-out",method: :delete%>
        </li>

    </ul>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tayar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Include style per-controller - vendor plugins -->


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>
            <%= render 'layouts/messages'%>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->
    </div>
    <!-- End wrapper-->

 <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tayar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Include style per-controller - vendor plugins -->


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <%= render 'layouts/messages'%>

    <!-- Main view  -->
    <%= yield %>

 <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/tracks/_form.html.erb
<div class="ibox-content">
  <%= form_for @track, :html=>{:class => "form-horizontal" ,:multipart => true} do |f| %>
    <div class="form-group"><label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
          <%= f.text_field :name, class:"form-control"%>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Track Length</label>
        <div class="col-sm-10">
          <%= f.number_field :length, class:"form-control" %>
        </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Select Artists</label>
      <div class="col-sm-10">
          <%= f.collection_select(:artist_id,@artists, :id, :name,class: "form-control m-b") %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Select Category</label>
      <div class="col-sm-10">
          <%= f.collection_select(:category_id,@categories, :id, :name,class: "form-control m-b") %>
      </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Image Upload</label>
        <div class="col-sm-10">
          <%= f.file_field :image_url, class:"form-control" %>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Subtitle Upload</label>
        <div class="col-sm-10">
          <%= f.file_field :translate_text, class:"form-control" %>
        </div>
    </div>
    <div class="form-group"><label class="col-sm-2 control-label">Track Upload</label>
        <div class="col-sm-10">
          <%= f.file_field :track_url, class:"form-control" %>
        </div>
    </div>


    <div class="form-group"><label class="col-sm-2 control-label">Track Description</label>
        <div class="col-sm-10">
          <%= f.text_area :description, class:"form-control summernote"%>
        </div>
    </div>

    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-2">
            <%= link_to "Cancel", tracks_path, class: "btn btn-white"%>
            <%= f.submit(@track.new_record? ? "Create Track" : "Edit Track", class: "btn btn-primary")%>
        </div>
    </div>
  <% end %>
</div>

<% content_for :javascript do %>
<script type="text/javascript">


$(function() {
    $('.summernote').summernote();
});

</script>
<% end %>

app/views/tracks/edit.html.erb
<%= render '/layouts/errors', obj: @track%>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Edit New Track</h5>
            </div>
            <div class="ibox-content">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/tracks/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
        <h2>Tracks

        </h2>
        <ol class="breadcrumb">
          <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'index' %>">Home</a>
          </li>
          <li class="active">
              <strong>Track List</strong>
          </li>
        </ol>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
      <div class="col-lg-12">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5>Track List</h5>
                  <div class="ibox-tools">
                    <%= link_to "Create", new_track_path, class:"btn btn-info btn-xs"%>
                    </div>
              </div>
              <div class="ibox-content">
                  <table class="table">
                      <thead>
                      <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Category Name</th>
                          <th>Artist Name</th>
                          <th>Length</th>
                      </tr>
                      </thead>
                      <tbody>
                      <% @tracks.each do |track|%>
                        <tr>
                            <td><%= track.id%></td>
                            <td><%= track.name%></td>
                            <td><%= track.category.name%></td>
                            <td><%= track.artist.name%></td>
                            <td><%= track.length%></td>
                            <td>
                              <%= link_to "show", track_path(track), class:"btn btn-primary btn-xs" %>
                              <%= link_to "Edit", edit_track_path(track), class:"btn btn-info btn-xs" %>
                              <%= link_to "Delete", track_path(track), method: :delete, data: {confirm: "Are you sure to delete track?"}, class:"btn btn-danger btn-xs"%>
                            </td>
                        </tr>
                      <% end %>
                      </tbody>
                  </table>

              </div>
          </div>
      </div>
  </div>
</div>

app/views/tracks/new.html.erb
<%= render '/layouts/errors', obj: @track%>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Create New Track</h5>
            </div>
            <div class="ibox-content">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<%= audio_tag url_for(@track.track_url), controls: true if @track.track_url.attached? %>